spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SNS?serverTimezone=UTC
    username: root
    password: tiger1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: fast_campus.sns-application-2024.secret_key
  # 30days
  token.expired-time-ms: 2592000000